apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: database
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
  serviceName: "mariadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
        # annotations:
        #   container.apparmor.security.beta.kubernetes.io/mariadb: runtime/default
    spec:
      serviceAccountName: database-sa
      nodeSelector:
        tier: database
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - backend
      # imagePullSecrets:
      # - name: pull-secret
      containers:
      - name: mariadb
        image: mariadb:11.4.2-ubi
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_DATABASE
          value: symfonydb
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        volumeMounts:
        - name: mariadb-conf
          mountPath: /etc/mysql/conf.d
        - name: mariadb-data
          mountPath: /var/lib/mysql
        securityContext:
          allowPrivilegeEscalation: false
          # securityContext:
          #   seccompProfile:
          #     type: RuntimeDefault
  volumeClaimTemplates:
  - metadata:
      name: mariadb-conf
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: mariadb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: database
spec:
  selector:
    app: mariadb
    tier: database
  type: ClusterIP # ClusterIP, NodePort, LoadBalancer, ExternalName
  ports:
  - port: 3306
    targetPort: 3306
